# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-29 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200526_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subject',
            field=models.CharField(choices=[('English', 'English'), ('Irish', 'Irish'), ('Maths', 'Maths'), ('Science', 'Science'), ('SESE', 'SESE'), ('Science_SESE', 'Science/SESE'), ('Geograghy', 'Geograghy'), ('History', 'History')], default='', max_length=40),
        ),
    ]
